# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN(1e12321e-10cc-4ba1-af96-643b3ca05ace)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Login to ACR
      az acr login --name sd2139frontend

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    # Ensure this is the name of your service connection in Azure DevOps
    azureSubscriptionConnection: 'Visual Studio Enterprise Subscription – MPN(1e12321e-10cc-4ba1-af96-643b3ca05ace)'
    # Ensure these values match your Azure Resource Group and AKS cluster
    azureResourceGroup: 'sd2139-rg'
    kubernetesCluster: 'myAKSCluster'
    useClusterAdmin: true
    # Ensure this namespace exists in your AKS cluster
    namespace: 'default'
    # Ensure this path is correct and points to your Kubernetes manifest file
    manifests: './k8s/frontend.yaml'
